apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.cloudest.artifakt.io
spec:
  group: cloudest.artifakt.io
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                imageName:
                  type: string
                replicas:
                  type: integer
            status:
              type: object
              properties:
                deploymentRefNamespace:
                  type: string
                deploymentRefName:
                  type: string
  names:
    plural: applications
    singular: application
    kind: Application
    shortNames:
      - app